import requests



# URL do endpoint da sua API
url = "https://sag-sag.rak8a3.easypanel.host/api/alunos/batch"


alunos = [
  {"nome": "ADA NICOLLY LIMA VIANA", "escola_id": 29, "turma_id": 98},
  {"nome": "ARIANA ALVES MAIA", "escola_id": 29, "turma_id": 98},
  {"nome": "ARTHUR ARAUJO DOS SANTOS NINA", "escola_id": 29, "turma_id": 98},
  {"nome": "ADRYAN MIGUEL MONTELO NASCIMENTO", "escola_id": 29, "turma_id": 98},
  {"nome": "LORENZO KAUAN CAMPOS BARBOSA", "escola_id": 29, "turma_id": 98},
  {"nome": "LIVIA SILVA PEREIRA", "escola_id": 29, "turma_id": 98},
  {"nome": "MARIA CLARA CUNHA AZEVEDO", "escola_id": 29, "turma_id": 98},
  {"nome": "MARIA CECILIA CUNHA AZEVEDO", "escola_id": 29, "turma_id": 98},
  {"nome": "MARIA ALICE DOS SANTOS GOMES", "escola_id": 29, "turma_id": 98},
  {"nome": "MANUELLY VITORIA CASTRO DOS SANTOS", "escola_id": 29, "turma_id": 98},
  {"nome": "SAMANTHA VITORIA VIEIRA ALVES", "escola_id": 29, "turma_id": 98},
  {"nome": "MARIANA SOUSA RAMOS", "escola_id": 29, "turma_id": 98},
  {"nome": "SHAIMON SOUSA RAMOS", "escola_id": 29, "turma_id": 98},
  {"nome": "MARIA CLARA SANTOS FERREIRA", "escola_id": 29, "turma_id": 98},
  {"nome": "EDGAR DE ASSUNCAO SILVA SANTOS JUNIOR", "escola_id": 29, "turma_id": 98},
  {"nome": "WANDERSON GUILHERME DE ARAUJO DO NASCIMENTO", "escola_id": 29, "turma_id": 98},
  {"nome": "THAYLA SAFIRA NASCIMENTO DE SOUSA", "escola_id": 29, "turma_id": 98},
  {"nome": "HADASSA EMANUELE SOUSA SÁ", "escola_id": 29, "turma_id": 98},
  {"nome": "HEITOR CARDOZO LIMA", "escola_id": 29, "turma_id": 98},
  {"nome": "NAYLSON KALEBE FEITOSA DOS SANTOS", "escola_id": 29, "turma_id": 98},
  {"nome": "NADSON DANIEL OLIVEIRA ROCHA", "escola_id": 29, "turma_id": 98},
  {"nome": "YASMIN KETLEN RIBEIRO CRUZ", "escola_id": 29, "turma_id": 98},
  {"nome": "MARIA GABRIELLY SOFIA ANDRADE DE CARVALHO", "escola_id": 29, "turma_id": 98},
  {"nome": "RENAN WENDELL LIMA COLINS", "escola_id": 29, "turma_id": 98},
  
  {"nome": "ALANA VITORIA SILVA AGYEMANG", "escola_id": 29, "turma_id": 99},
  {"nome": "ANA VALENTINA SANTOS SILVA", "escola_id": 29, "turma_id": 99},
  {"nome": "AYLLA SOPHIA DOS SANTOS ROSA", "escola_id": 29, "turma_id": 99},
  {"nome": "BENJAMIN VICENTE AGUIAR DA COSTA", "escola_id": 29, "turma_id": 99},
  {"nome": "EMERSON KAWAN NASCIMENTO SANTOS", "escola_id": 29, "turma_id": 99},
  {"nome": "HENDERSON SANTOS LIMA", "escola_id": 29, "turma_id": 99},
  {"nome": "ISILY ESTER FEITOSA DOS SANTOS", "escola_id": 29, "turma_id": 99},
  {"nome": "IZABELA LOPES COELHO", "escola_id": 29, "turma_id": 99},
  {"nome": "JAILSON SANTOS VIERA", "escola_id": 29, "turma_id": 99},
  {"nome": "JEOVANNA DHANDARA CARVALHO DE ARAUJO", "escola_id": 29, "turma_id": 99},
  {"nome": "JOÃO GUILHERME RABELO PEREIRA", "escola_id": 29, "turma_id": 99},
  {"nome": "LAYZA VALENTINA DOS SANTOS PINHEIRO", "escola_id": 29, "turma_id": 99},
  {"nome": "LAYLLA HADASSA DA SILVEIRA DE OLIVEIRA", "escola_id": 29, "turma_id": 99},
  {"nome": "LAYLA VITORIA SOUSA DA CRUZ", "escola_id": 29, "turma_id": 99},
  {"nome": "LEANDERSON LUIS BATISTA BRAGA", "escola_id": 29, "turma_id": 99},
  {"nome": "LUAN CARLOS PIRES FREIRE", "escola_id": 29, "turma_id": 99},
  {"nome": "LUENNA ISABELA SOUSA RODRIGUES", "escola_id": 29, "turma_id": 99},
  {"nome": "LUIZA BEATRIZ SILVA SOUZA", "escola_id": 29, "turma_id": 99},
  {"nome": "MAYSA CAVALCANTE DOS SANTOS", "escola_id": 29, "turma_id": 99},
  {"nome": "SAFIRA SOUSA PINHEIRO", "escola_id": 29, "turma_id": 99},
  {"nome": "THAISSA RAQUEL ROCHA DOS SANTOS", "escola_id": 29, "turma_id": 99},
  {"nome": "THAYLA YASMIN CONCEICAO BARBOSA", "escola_id": 29, "turma_id": 99},
  {"nome": "THALLYA VITORIA DINIZ COSTA", "escola_id": 29, "turma_id": 99},
  {"nome": "WESLEY HENRIQUE SOARES DA SILVA", "escola_id": 29, "turma_id": 99},

  {"nome": "CAIO VINICIUS SANTOS MARTINS", "escola_id": 29, "turma_id": 100},
  {"nome": "CARLOS HENRIQUE RODRIGUES MENESES", "escola_id": 29, "turma_id": 100},
  {"nome": "DAVI LUCAS RODRIGUES SOUZA", "escola_id": 29, "turma_id": 100},
  {"nome": "EMILLY MANUELY DUTRA LIMA", "escola_id": 29, "turma_id": 100},
  {"nome": "FELIPE ROGERIO SANTOS SILVA", "escola_id": 29, "turma_id": 100},
  {"nome": "HILLARY LAUANE ARAUJO RODRIGUES", "escola_id": 29, "turma_id": 100},
  {"nome": "JOÃO MIGUEL LORENO DOS SANTOS", "escola_id": 29, "turma_id": 100},
  {"nome": "JOÃO DAVI GOMES VIANA", "escola_id": 29, "turma_id": 100},
  {"nome": "JOAO VICTOR MONTEIRO DA SILVA", "escola_id": 29, "turma_id": 100},
  {"nome": "LAUANY RODRIGUES ARAUJO", "escola_id": 29, "turma_id": 100},
  {"nome": "LANA SOFIA VIEIRA DOS SANTOS", "escola_id": 29, "turma_id": 100},
  {"nome": "LUCAS DOS SANTOS NASCIMENTO", "escola_id": 29, "turma_id": 100},
  {"nome": "LUCAS YAGO PIRES SANTOS", "escola_id": 29, "turma_id": 100},
  {"nome": "MARIA HELLOYSA DA SILVA BATISTA", "escola_id": 29, "turma_id": 100},
  {"nome": "ARYANE SANTOS ALENCAR", "escola_id": 29, "turma_id": 100},
  {"nome": "MIRELLA SOPHIA REIS ALVES", "escola_id": 29, "turma_id": 100},
  {"nome": "NICOLLAS GABRIEL FERREIRA COELHO", "escola_id": 29, "turma_id": 100},
  {"nome": "RHYAN GUILHERME DUARTE DOS SANTOS", "escola_id": 29, "turma_id": 100},
  {"nome": "SAFIRA OLIVEIRA DOS SANTOS", "escola_id": 29, "turma_id": 100},
  {"nome": "SAYMON HENRICK SILVA PIRES", "escola_id": 29, "turma_id": 100},
  {"nome": "THIAGO FELIPE DE SOUSA ARAUJO", "escola_id": 29, "turma_id": 100},
  {"nome": "YMAYLD DA SILVA RODRIGUES", "escola_id": 29, "turma_id": 100},
  {"nome": "YTALO MOISES SANTOS ARAUJO", "escola_id": 29, "turma_id": 100},
  
  {"nome": "ADRIELE RAISSA DA SILVA DE ASSIS", "escola_id": 29, "turma_id": 101},
  {"nome": "ALICE MARIANA RABELO LOBO", "escola_id": 29, "turma_id": 101},
  {"nome": "ANA JULIA MENDES CASTRO", "escola_id": 29, "turma_id": 101},
  {"nome": "ARTHUR RHYAN DE PAULA GOMES AZEVEDO", "escola_id": 29, "turma_id": 101},
  {"nome": "BRUNA BIANCA COSTA", "escola_id": 29, "turma_id": 101},
  {"nome": "BRYAN LUCCA BATISTA DOS SANTOS SALME", "escola_id": 29, "turma_id": 101},
  {"nome": "IARA SAFIRA BARBOSA ALVES", "escola_id": 29, "turma_id": 101},
  {"nome": "JARDSON DA COSTA SANTOS", "escola_id": 29, "turma_id": 101},
  {"nome": "JOAO AUGUSTO BRAGA SOUSA", "escola_id": 29, "turma_id": 101},
  {"nome": "JOAO GABRIEL FERREIRA GASPAR", "escola_id": 29, "turma_id": 101},
  {"nome": "JOSEPHY GABRYELL NOGUEIRA DUARTE", "escola_id": 29, "turma_id": 101},
  {"nome": "LIVIA LAVINY DOS SANTOS FRAZAO", "escola_id": 29, "turma_id": 101},
  {"nome": "LUIZ GUSTAVO ALVES COUTINHO", "escola_id": 29, "turma_id": 101},
  {"nome": "MARIA PAULA DOS SANTOS COSTA", "escola_id": 29, "turma_id": 101},
  {"nome": "MANUELLY VITORIA TORRES DA SILVA", "escola_id": 29, "turma_id": 101},
  {"nome": "MARIA VITORIA BATISTA DOS SANTOS", "escola_id": 29, "turma_id": 101},
  {"nome": "PAULO GABRIEL MENDES LISBOA", "escola_id": 29, "turma_id": 101},
  {"nome": "PEDRO LUCAS REIS MENDES", "escola_id": 29, "turma_id": 101},
  {"nome": "RENAN SANTOS LIMA", "escola_id": 29, "turma_id": 101},
  {"nome": "RICHARLLYSON MOISES PEREIRA BRASIL", "escola_id": 29, "turma_id": 101},
  {"nome": "RON BENJAMIM SOARES DE OLIVEIRA", "escola_id": 29, "turma_id": 101},
  {"nome": "SARAH EVILYN GOMES SANTOS", "escola_id": 29, "turma_id": 101},
  {"nome": "VICTOR HUGO NASCIMENTO", "escola_id": 29, "turma_id": 101},
  {"nome": "YASMIN DA SILVA CRUZ", "escola_id": 29, "turma_id": 101},
  
  {"nome": "ANNA BEATRIZ MEDEIROS GONCALVES", "escola_id": 29, "turma_id": 102},
  {"nome": "ANA CAROLINE MATOS DOS SANTOS", "escola_id": 29, "turma_id": 102},
  {"nome": "CARLOS HENRIQUE LIMA CASTRO", "escola_id": 29, "turma_id": 102},
  {"nome": "ERLANDO KAIO OLIVEIRA MENDES", "escola_id": 29, "turma_id": 102},
  {"nome": "ENZO GABRIEL MARTINS AMORIM", "escola_id": 29, "turma_id": 102},
  {"nome": "EMANUELLE DE ASSUNCAO COSTA", "escola_id": 29, "turma_id": 102},
  {"nome": "EMANUEL SANTOS REIS", "escola_id": 29, "turma_id": 102},
  {"nome": "JOSUE DOS SANTOS ARAUJO", "escola_id": 29, "turma_id": 102},
  {"nome": "ISABELLE VICTORIA MARTINS CASTELO BRANCO", "escola_id": 29, "turma_id": 102},
  {"nome": "JHONATAN SOUZA GARCIA", "escola_id": 29, "turma_id": 102},
  {"nome": "JULLYA HADASSA COSTA DANTAS", "escola_id": 29, "turma_id": 102},
  {"nome": "KAMILLY VITORIA LOPES COELHO", "escola_id": 29, "turma_id": 102},
  {"nome": "LEONARDO RODRIGUES ARAUJO", "escola_id": 29, "turma_id": 102},
  {"nome": "LEVI AUGUSTO SILVA PEREIRA", "escola_id": 29, "turma_id": 102},
  {"nome": "LUCAS EMANUEL SILVA BATISTA", "escola_id": 29, "turma_id": 102},
  {"nome": "LUIS MIGUEL SILVA LISBOA", "escola_id": 29, "turma_id": 102},
  {"nome": "MARIA CLARA CASTRO VILAS BOAS FERREIRA", "escola_id": 29, "turma_id": 102},
  {"nome": "MAURO SERGIO REIS AMARAL", "escola_id": 29, "turma_id": 102},
  {"nome": "MELISSA VICTORIA SANTOS DA SILVA", "escola_id": 29, "turma_id": 102},
  {"nome": "MICHEL FILIPE LOPES DOS SANTOS", "escola_id": 29, "turma_id": 102},
  {"nome": "NAYANNY SANTOS ARAUJO", "escola_id": 29, "turma_id": 102},
  {"nome": "NICHOLLAS GABRIEL SA DOS SANTOS", "escola_id": 29, "turma_id": 102},
  {"nome": "NICOLE CRISTINA RODRIGUES RABELO", "escola_id": 29, "turma_id": 102},
  {"nome": "PEROLA ESTHEFANE SILVA DOS SANTOS", "escola_id": 29, "turma_id": 102},
  {"nome": "SAFIRA VITORIA DE OLIVEIRA LIMA", "escola_id": 29, "turma_id": 102},
  {"nome": "THAYSON SAMUEL SILVA SOUZA", "escola_id": 29, "turma_id": 102},
  
  {"nome": "ESTHER LAIS MADEIRA FERREIRA", "escola_id": 29, "turma_id": 103},
  {"nome": "LAURA GONCALVES DE OLIVEIRA", "escola_id": 29, "turma_id": 103},
  {"nome": "LAUANE CRISTINA VIEIRA DOS SANTOS", "escola_id": 29, "turma_id": 103},
  {"nome": "MARIA JULIA MENDES SILVA", "escola_id": 29, "turma_id": 103},
  {"nome": "ELYZEU SANTOS E SANTOS", "escola_id": 29, "turma_id": 103},
  {"nome": "JORLANDO CESAR FELIX SILVA", "escola_id": 29, "turma_id": 103},
  {"nome": "JULIANA COELHO SANTOS", "escola_id": 29, "turma_id": 103},
  {"nome": "KAYK GABRIEL DE JESUS SALAZAR", "escola_id": 29, "turma_id": 103},
  {"nome": "KELLY MELISSA SANTOS ALMEIDA", "escola_id": 29, "turma_id": 103},
  {"nome": "YNGRID DA SILVA RODRIGUES", "escola_id": 29, "turma_id": 103},
  {"nome": "TITO SAYMON SOARES DE OLIVEIRA", "escola_id": 29, "turma_id": 103},
  {"nome": "THALISON THIAGO NERES ROCHA", "escola_id": 29, "turma_id": 103},
  {"nome": "THALYSON GABRIEL TRINDADE MARTINS", "escola_id": 29, "turma_id": 103},
  {"nome": "VICTORIA MARYANE COSTA FRAZAO", "escola_id": 29, "turma_id": 103},
  
  {"nome": "ADRIELE ARAUJO DOS SANTOS FERREIRA", "escola_id": 29, "turma_id": 104},
  {"nome": "ANA BEHATRIZ RAMOS NASCIMENTO", "escola_id": 29, "turma_id": 104},
  {"nome": "ANA CLARA DIAS RIBEIRO", "escola_id": 29, "turma_id": 104},
  {"nome": "ADRIANA ARAUJO DOS SANTOS NINA", "escola_id": 29, "turma_id": 104},
  {"nome": "ALLEXYA VALLENTINA SILVA DE AZEVEDO", "escola_id": 29, "turma_id": 104},
  {"nome": "CARLOS DANIEL MATOS SILVA", "escola_id": 29, "turma_id": 104},
  {"nome": "DANIEL LUCCA SILVA REIS", "escola_id": 29, "turma_id": 104},
  {"nome": "EMILLY SOFHIA DA SILVA SOUZA", "escola_id": 29, "turma_id": 104},
  {"nome": "ENZO GABRYEL ALVES SILVA", "escola_id": 29, "turma_id": 104},
  {"nome": "HELLEN MARIA SANTOS RODRIGUES", "escola_id": 29, "turma_id": 104},
  {"nome": "HENRIQUE SOUSA RAMOS", "escola_id": 29, "turma_id": 104},
  {"nome": "JOSUE SILVA GARCES DA SILVA", "escola_id": 29, "turma_id": 104},
  {"nome": "KALEB GABRIEL DE JESUS SALAZAR", "escola_id": 29, "turma_id": 104},
  {"nome": "KAYLON KAUE SOBRINHO DA SILVA", "escola_id": 29, "turma_id": 104},
  {"nome": "MATEUS FELIPE DA SILVA GOMES", "escola_id": 29, "turma_id": 104},
  {"nome": "NICOLY SOPHIA FONSECA FRAZAO", "escola_id": 29, "turma_id": 104},
  {"nome": "ORLANDO PINHEIRO DOS SANTOS NETO", "escola_id": 29, "turma_id": 104},
  {"nome": "ROBSON MIGUEL MENDES FONTILENE", "escola_id": 29, "turma_id": 104},
  {"nome": "WYNDSON MIGUEL SOUZA ABREU", "escola_id": 29, "turma_id": 104},
  {"nome": "YASMIN SOPHIA PEREIRA SOUSA", "escola_id": 29, "turma_id": 104},
  {"nome": "YURE WILKER DE CARVALHO LOPES", "escola_id": 29, "turma_id": 104},
  {"nome": "MIKAELLY DOS SANTOS SILVA", "escola_id": 29, "turma_id": 104},
  {"nome": "LUCAS DANIEL REIS DOS SANTOS", "escola_id": 29, "turma_id": 104},
  
  {"nome": "ALEXSANDRO DAYVEN NOGUEIRA LIMA", "escola_id": 29, "turma_id": 105},
  {"nome": "ANA ISABELLY DOS SANTOS FRAZAO", "escola_id": 29, "turma_id": 105},
  {"nome": "ANA JULIA RABELO LOPES", "escola_id": 29, "turma_id": 105},
  {"nome": "ANA LORRANY DE OLIVEIRA SILVA", "escola_id": 29, "turma_id": 105},
  {"nome": "ANTONENY KAILANE SILVA VIEIRA", "escola_id": 29, "turma_id": 105},
  {"nome": "BRUNO LUIS SANTOS E SANTOS", "escola_id": 29, "turma_id": 105},
  {"nome": "ERIKA AMANDA REIS FERREIRA", "escola_id": 29, "turma_id": 105},
  {"nome": "HIAGO DAMIAO BARBOSA ALVES", "escola_id": 29, "turma_id": 105},
  {"nome": "HIAGO THAUAN BARBOSA LIMA", "escola_id": 29, "turma_id": 105},
  {"nome": "ISABELLY SOPHIA CARVALHO ANDRADE", "escola_id": 29, "turma_id": 105},
  {"nome": "JEAN CARLOS BARBOSA SOARES", "escola_id": 29, "turma_id": 105},
  {"nome": "JOAO GABRIEL DUTRA SOUSA", "escola_id": 29, "turma_id": 105},
  {"nome": "JONYS DA COSTA SANTOS", "escola_id": 29, "turma_id": 105},
  {"nome": "LAYLA JULIA MENDES SILVA", "escola_id": 29, "turma_id": 105},
  {"nome": "MARCOS DAVI SOUSA AZEVEDO", "escola_id": 29, "turma_id": 105},
  {"nome": "MANUELA VALENTINA RIBEIRO", "escola_id": 29, "turma_id": 105},
  {"nome": "MICAELA BATISTA PINTO SILVA", "escola_id": 29, "turma_id": 105},
  {"nome": "MICAELI VITORIA DA SILVA FERREIRA", "escola_id": 29, "turma_id": 105},
  {"nome": "NALLYSON KAUAN MUNIZ DE JESUS", "escola_id": 29, "turma_id": 105},
  {"nome": "NETLY RAWANNY FERREIRA MENDES", "escola_id": 29, "turma_id": 105},
  {"nome": "SEBASTIAO WANDSON DO NASCIMENTO VIEIRA", "escola_id": 29, "turma_id": 105},
  {"nome": "SUELY GOMES DOS SANTOS", "escola_id": 29, "turma_id": 105},
  {"nome": "VITOR JOAKIM MADEIRA FERREIRA", "escola_id": 29, "turma_id": 105},
  {"nome": "VICTOR HUGO DOS SANTOS DA SILVA", "escola_id": 29, "turma_id": 105},
  {"nome": "WARDSON GUILHERME CORDEIRO SILVA", "escola_id": 29, "turma_id": 105},
  {"nome": "VINICIUS GABRIEL RODRIGUES MARTINS", "escola_id": 29, "turma_id": 105},
  {"nome": "DHIORLAN SANTOS E SANTOS", "escola_id": 29, "turma_id": 105},
  {"nome": "MARIA BEATRIZ DA SILVA RAMOS", "escola_id": 29, "turma_id": 105}
]
  


# Cabeçalhos, incluindo token se necessário
headers = {
    "Content-Type": "application/json"
}

# Enviando os dados para a API
response = requests.post(url, json=alunos, headers=headers)

# Verificando o resultado
if response.status_code in [200, 201]:
    print("Alunos cadastrados com sucesso!")
    #print(response.json())  # resposta da API
else:
    print("Erro ao cadastrar alunos:")
    print(f"Status: {response.status_code}")
    print(response.text)
